In [1]:
import numpy as np
import pandas as pd
import janitor

In [4]:
company_sales = {
    'SalesMonth': ['Jan', 'Feb', 'Mar', 'April'],
    'Company1': [150.0, 200.0, 300.0, 400.0],
    'Company2': [180.0, 250.0, np.nan, 500.0],
    'Company3': [400.0, 500.0, 600.0, 675.0]
}

In [5]:
#Pandas

# 1. Create a pandas DataFrame from the company_sales dictionary
df = pd.DataFrame.from_dict(company_sales)

# 2. Delete a column from the DataFrame. Say 'Company1'
del df['Company1']

# 3. Drop rows that have empty values in columns 'Company2' and 'Company3'
df = df.dropna(subset=['Company2', 'Company3'])

# 4. Rename 'Company2' to 'Amazon' and 'Company3' to 'Facebook'
df = df.rename(
    {
        'Company2': 'Amazon',
        'Company3': 'Facebook',
    },
    axis=1,
)

# 5. Let's add some data for another company. Say 'Google'
df['Google'] = [450.0, 550.0, 800.0]

df

  SalesMonth  Amazon  Facebook  Google
0        Jan   180.0     400.0   450.0
1        Feb   250.0     500.0   550.0
3      April   500.0     675.0   800.0

In [6]:
#More Advanced Users

df = (
    pd.DataFrame(company_sales)
    .drop(columns="Company1")
    .dropna(subset=["Company2", "Company3"])
    .rename(columns={"Company2": "Amazon", "Company3": "Facebook"})
    .assign(Google=[450.0, 550.0, 800.0])
)

df

  SalesMonth  Amazon  Facebook  Google
0        Jan   180.0     400.0   450.0
1        Feb   250.0     500.0   550.0
3      April   500.0     675.0   800.0

In [7]:
#PyJanitor

#uses method chaining that are verbs

df = (
    pd.DataFrame.from_dict(company_sales)
    .remove_columns(["Company1"])
    .dropna(subset=["Company2", "Company3"])
    .rename_column("Company2", "Amazon")
    .rename_column("Company3", "Facebook")
    .add_column("Google", [450.0, 550.0, 800.0])
)

df

/Users/johnbonanno/venvs/jupyter-env/lib/python3.14/site-packages/pandas_flavor/register.py:161: FutureWarning: This function will be deprecated in a 1.x release. Please use `pd.DataFrame.drop` instead.
  return method(self._obj, *args, **kwargs)
/Users/johnbonanno/venvs/jupyter-env/lib/python3.14/site-packages/pandas_flavor/register.py:161: FutureWarning: This function will be deprecated in a 1.x release. Please use `pd.DataFrame.rename` instead.
  return method(self._obj, *args, **kwargs)
/Users/johnbonanno/venvs/jupyter-env/lib/python3.14/site-packages/pandas_flavor/register.py:161: FutureWarning: This function will be deprecated in a 1.x release. Please use `pd.DataFrame.assign` instead.
  return method(self._obj, *args, **kwargs)

  SalesMonth  Amazon  Facebook  Google
0        Jan   180.0     400.0   450.0
1        Feb   250.0     500.0   550.0
3      April   500.0     675.0   800.0

Personal preference, but for worse, code assist probably makes this not a big deal either way